server {
    listen 80;
    server_name urlaub.birghan-dev.de;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name urlaub.birghan-dev.de;

    ssl_certificate     /etc/letsencrypt/live/urlaub.birghan-dev.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/urlaub.birghan-dev.de/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    resolver 127.0.0.11 valid=30s;

    location /api/auth/login {
        limit_req zone=login burst=5 nodelay;
        set $backend http://backend:8000;
        proxy_pass         $backend;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/ {
        set $backend http://backend:8000;
        proxy_pass         $backend;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location / {
        set $frontend http://frontend:80;
        proxy_pass         $frontend;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }
}
